export const API_OPTION = {
  TRENDING: "trending",
  UPCOMMING_MOVIES: "upcomming_movies",
  NOW_PLAYING: "now_playing",
  MOVIE: "movie",
  TOP_RATED: "top_rated",
  POPULAR: "popular",
  POPULAR_TV: "popular_tv",
  PROVIDER: "provider",
  TV: "tv",
  SIMILAR: "similar",
  SIMILAR_TV: "similar_tv",
  RECOMMENDATIONS: "recommendations",
  ON_THE_AIR: "on_the_air",
  SEASON: "season",
  MOVIE_CAST: "movie_cast",
  TV_CAST: "tv_cast",
  VIDEO_URL: "videos",
  PEOPLE: "people",
  CREDITS: "credits",
  DISCOVER_MOVIE: "discover_movie",
  DISCOVER_TV: "discover_tv",
};

export const BASE_URL_IMAGE = "https://image.tmdb.org/t/p/original/";
