import Head from "next/head";
import type { ReactElement } from "react";
import Header from "../components/global/Header";
import { APP_NAME } from "../utils/appConfig";
import { AnimatePresence, LazyMotion, m } from "framer-motion";
import { SearchProvider,  } from "../context/search";
import dynamic from "next/dynamic";
import "lazysizes";
import "lazysizes/plugins/parent-fit/ls.parent-fit";
import NextNProgress from 'nextjs-progressbar';


// import "lazysizes/plugins/native-loading/ls.native-loading";

// lazySizes.cfg.nativeLoading = {
//   setLoadingAttribute: true,
//   disableListeners: {
//     scroll: true,
//   },
// };

const loadFeatures = () => import("../utils/domMax").then((mod) => mod.DomMax);
const DynamicSearch = dynamic(() => import("../components/global/Search"));

function Layout(props: { children: ReactElement }) {
  return (
    <>
    <NextNProgress color="#10b981" height={4}/>
    <AnimatePresence mode="wait">
      <SearchProvider>
        <>
          <Head>
            <title>{APP_NAME}</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <DynamicSearch />
          <Header />
          <LazyMotion features={loadFeatures} strict>
            <m.main
              exit={{ opacity: 0 }}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1, transition: { duration: 0.5 } }}
              className="min-h-screen"
            >
              {props.children}
            </m.main>
          </LazyMotion>
        </>
      </SearchProvider>
    </AnimatePresence>
    </>
  );
}

export default Layout;
